### ISSUE TITLE
Identifier does not contain an object definition

### ISSUE THREAD

**Issue by jlem** [silexphp/Pimple#186]
I'm trying to completely override / replace a service container definition.

I can't just assign a new anonymous function because it complains about a frozen service. Yet when I try 

```php
$container->extend('my.service', function($oldService, $c) {
    return new Replacement();
}
```

It throws the object definition error.

How do you actually replace a service definition in Pimple?

**Comment by stof** [comment]
@jlem overwriting a service definition is possible only before retrieving the service instance (this is what "frozen service" means). You should separate the building of your container from its usage.

Extending a service once it has been instantiated cannot have an effect, as it is already instantiated. and the reason it does not work is because the internal storage of a frozen service changes (for performance reason) so it tries to extend the instance rather than the service definition.
We should add a validation of this case to give a better exception message when trying to extend a frozen service though.

**Comment by jlem** [comment]
That's what I'm confused about. I have a flat configuration file where I wire-up and construct all of my services up front. This is services.php. No usage happens here, it's just configuration.

I then include that file in another script, and I want to replace one service definition.

It literally looks like this:

```php
// in scripts.php
$services = require 'services.php';
$services['my.service', function($c) {
    return ReplacementSercvice;
});

// start resolving the services down here....
```

But that triggers the frozen error.

**Comment by stof** [comment]
@jlem can you show the content of services.php ? I think you might have a place where you define a service in the wrong way and trigger the instantiation of another one because of that
