### ISSUE TITLE
Strange behaviour in getting value from $app

### ISSUE THREAD

**Issue by marcelloh** [silexphp/Pimple#215]
Somewhere in my (silex) code I have:
```
// from github morris/dop
$db = new \Dop\Connection( $db );
$app['db'] = $db;
```
and then later on
```
$db = $app['db'];
```
If I debug on that last line, it still has a \Dop\Connection inside, but after that line,
the $app['db'] value has changed.
I didn't expect it from a getter, and I never have seen that effect before.
(it is changed into a \Dop\Fragment now)

In the Container->offsetGet, I see on line 112, that $raw has the correct value, but it gets overwritten by the $val of line 113. Actually the $raw($this) is causing it.

Any hints in how to solve this behviour?

**Comment by stof** [comment]
the issue is that ``Dop\Connection`` is a callable object. By default, setting a callable in Pimple sets a service definition (which is executed when asking to get the service).
Pimple is not just an ArrayObject. It is a container instantiating services *lazily* (this is its main feature).

The clean solution for your problem is to keep the instantiation of your service lazy, by using a proper service definition:

```php
$app['db'] = function ($c) {
    return new \Dop\Connection(...);
};

// later on 
$db = $app['db']; // the Connection gets instantiated by Pimple at this point for the first access to it
```

If you insist on instantiating the service yourselves (for a weird reason), you can still make it work by protecting the callable object (so that Pimple knows that you want to store the callable itself as the service):

```php
$db = new \Dop\Connection( $db );
$app['db'] = $app->protect($db);
```
